-- MySQL Script generated by MySQL Workbench
-- Wed Oct  1 12:13:46 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Policies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Policies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Policies` (
  `PolID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Attempts` INT NOT NULL,
  `Timed` VARCHAR(1) NOT NULL,
  `TimeLimit` INT NULL,
  `ShowAns` VARCHAR(1) NOT NULL,
  `Scored` VARCHAR(1) NOT NULL,
  `Grade` INT NOT NULL,
  `ShuffleQues` VARCHAR(1) NOT NULL,
  `ShuffleAns` VARCHAR(1) NOT NULL,
  `AccessCode` VARCHAR(255) NULL,
  PRIMARY KEY (`PolID`),
  UNIQUE INDEX `PolID_UNIQUE` (`PolID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DisplayElements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DisplayElements` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DisplayElements` (
  `DispElID` INT NOT NULL AUTO_INCREMENT COMMENT 'Not sure I\'ll need this but needed for diagram i think',
  PRIMARY KEY (`DispElID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Quizzes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Quizzes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Quizzes` (
  `QuizID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Desc` INT NULL,
  `Policy` INT NOT NULL,
  `Privacy` CHAR(1) NOT NULL,
  PRIMARY KEY (`QuizID`),
  UNIQUE INDEX `QID_UNIQUE` (`QuizID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Questions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Questions` (
  `QuesID` INT NOT NULL AUTO_INCREMENT,
  `Points` INT NOT NULL,
  `Level` INT NULL,
  `Type` CHAR(4) NOT NULL,
  PRIMARY KEY (`QuesID`),
  UNIQUE INDEX `QuesID_UNIQUE` (`QuesID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Courses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Courses` (
  `CourseID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Privacy` CHAR(1) NOT NULL,
  PRIMARY KEY (`CourseID`),
  UNIQUE INDEX `CID_UNIQUE` (`CourseID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CoursesQuizzes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CoursesQuizzes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CoursesQuizzes` (
  `Course` INT NULL,
  `Quiz` INT NULL,
  `Order` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QuesCon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`QuesCon` ;

CREATE TABLE IF NOT EXISTS `mydb`.`QuesCon` (
  `QuesConID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`QuesConID`),
  UNIQUE INDEX `QCID_UNIQUE` (`QuesConID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QuizzesQuesCons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`QuizzesQuesCons` ;

CREATE TABLE IF NOT EXISTS `mydb`.`QuizzesQuesCons` (
  `Quiz` INT NOT NULL,
  `QuesCon` INT NOT NULL,
  `Order` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QuesConElements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`QuesConElements` ;

CREATE TABLE IF NOT EXISTS `mydb`.`QuesConElements` (
  `QuesCon` INT NOT NULL,
  `Order` INT NOT NULL,
  `Element` INT NULL,
  `Ques` INT NULL,
  `Type` CHAR(4) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Answers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Answers` (
  `AnsID` INT NOT NULL,
  `Order` INT NOT NULL,
  `Correct` VARCHAR(1) NOT NULL DEFAULT 'Y',
  `Response` INT NULL,
  `Element` INT NULL COMMENT 'What represents the answer',
  `LowBound` INT NULL COMMENT 'to accept a range of numbers (lower bound)',
  `HighBound` INT NULL COMMENT 'to accept a range of numbers (upper bound)',
  PRIMARY KEY (`AnsID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DispElSeq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DispElSeq` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DispElSeq` (
  `DispEl` INT NOT NULL,
  `Element` VARCHAR(255) NOT NULL,
  `Order` INT NOT NULL,
  `Type` CHAR(4) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StdChoices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`StdChoices` ;

CREATE TABLE IF NOT EXISTS `mydb`.`StdChoices` (
  `StdChoice` INT NOT NULL,
  `Element` INT NOT NULL,
  `Order` INT NOT NULL,
  PRIMARY KEY (`StdChoice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QuesAnsSeq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`QuesAnsSeq` ;

CREATE TABLE IF NOT EXISTS `mydb`.`QuesAnsSeq` (
  `Ques` INT NOT NULL,
  `Ans` INT NULL,
  `StdChoice` INT NULL,
  `Sequence` INT NULL,
  `Corrent` CHAR(1) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(255) NOT NULL,
  `LastName` VARCHAR(255) NOT NULL,
  `Username` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UsersCourses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UsersCourses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UsersCourses` (
  `User` INT NOT NULL,
  `Course` INT NOT NULL,
  `Role` CHAR(4) NOT NULL)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`ViewAnsToQues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ViewAnsToQues` (`Ques` INT, `GROUP_CONCAT(Ans)` INT, `GROUP_CONCAT(StdChoice)` INT, `Sequence` INT);

-- -----------------------------------------------------
-- View `mydb`.`ViewAnsToQues`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`ViewAnsToQues` ;
DROP TABLE IF EXISTS `mydb`.`ViewAnsToQues`;
USE `mydb`;
CREATE  OR REPLACE VIEW `ViewAnsToQues` AS 
SELECT Ques, GROUP_CONCAT(Ans), GROUP_CONCAT(StdChoice), Sequence
FROM QuesAnsSeq
WHERE Correct="Y"
;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
